//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartMirror.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartMirror.Resources.Strings.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessories.
        /// </summary>
        internal static string Accessories {
            get {
                return ResourceManager.GetString("Accessories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Favorites.
        /// </summary>
        internal static string AddToFavorites {
            get {
                return ResourceManager.GetString("AddToFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aqara.
        /// </summary>
        internal static string Aqara {
            get {
                return ResourceManager.GetString("Aqara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back Door.
        /// </summary>
        internal static string BackDoor {
            get {
                return ResourceManager.GetString("BackDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balcony Door.
        /// </summary>
        internal static string BalconyDoor {
            get {
                return ResourceManager.GetString("BalconyDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera is off.
        /// </summary>
        internal static string CameraIsOff {
            get {
                return ResourceManager.GetString("CameraIsOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cameras.
        /// </summary>
        internal static string Cameras {
            get {
                return ResourceManager.GetString("Cameras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t play this video.
        /// </summary>
        internal static string CannotPlayVideo {
            get {
                return ResourceManager.GetString("CannotPlayVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        internal static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dining Room.
        /// </summary>
        internal static string DiningRoom {
            get {
                return ResourceManager.GetString("DiningRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        internal static string Disconnected {
            get {
                return ResourceManager.GetString("Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downstairs.
        /// </summary>
        internal static string Downstairs {
            get {
                return ResourceManager.GetString("Downstairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Code.
        /// </summary>
        internal static string EnterCode {
            get {
                return ResourceManager.GetString("EnterCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error description.
        /// </summary>
        internal static string ErrorDescription {
            get {
                return ResourceManager.GetString("ErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fan.
        /// </summary>
        internal static string Fan {
            get {
                return ResourceManager.GetString("Fan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite Accessories.
        /// </summary>
        internal static string FavoriteAccessories {
            get {
                return ResourceManager.GetString("FavoriteAccessories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite Scenarios.
        /// </summary>
        internal static string FavoriteScenarios {
            get {
                return ResourceManager.GetString("FavoriteScenarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow all instructions and complete your registration.
        /// </summary>
        internal static string FollowAllInstructions {
            get {
                return ResourceManager.GetString("FollowAllInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday Night.
        /// </summary>
        internal static string FridayNight {
            get {
                return ResourceManager.GetString("FridayNight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front Door.
        /// </summary>
        internal static string FrontDoor {
            get {
                return ResourceManager.GetString("FrontDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garage.
        /// </summary>
        internal static string Garage {
            get {
                return ResourceManager.GetString("Garage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garage Door.
        /// </summary>
        internal static string GarageDoor {
            get {
                return ResourceManager.GetString("GarageDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good Evening.
        /// </summary>
        internal static string GoodEvening {
            get {
                return ResourceManager.GetString("GoodEvening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good Morning.
        /// </summary>
        internal static string GoodMorning {
            get {
                return ResourceManager.GetString("GoodMorning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Half Bath.
        /// </summary>
        internal static string HalfBath {
            get {
                return ResourceManager.GetString("HalfBath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HomePod.
        /// </summary>
        internal static string HomePod {
            get {
                return ResourceManager.GetString("HomePod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours ago.
        /// </summary>
        internal static string HoursAgo {
            get {
                return ResourceManager.GetString("HoursAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To continue using the app, please install our Configuration app on your smartphone..
        /// </summary>
        internal static string InstallConfigurationApp {
            get {
                return ResourceManager.GetString("InstallConfigurationApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Living Room.
        /// </summary>
        internal static string LivingRoom {
            get {
                return ResourceManager.GetString("LivingRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes ago.
        /// </summary>
        internal static string MinutesAgo {
            get {
                return ResourceManager.GetString("MinutesAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Needs two taps to exit the app..
        /// </summary>
        internal static string NeedsTwoTaps {
            get {
                return ResourceManager.GetString("NeedsTwoTaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No accessories yet.
        /// </summary>
        internal static string NoAccessoriesYet {
            get {
                return ResourceManager.GetString("NoAccessoriesYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No cameras yet.
        /// </summary>
        internal static string NoCamerasYet {
            get {
                return ResourceManager.GetString("NoCamerasYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No internet connection.
        /// </summary>
        internal static string NoInternetConnection {
            get {
                return ResourceManager.GetString("NoInternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No movement.
        /// </summary>
        internal static string NoMovement {
            get {
                return ResourceManager.GetString("NoMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No notifications yet.
        /// </summary>
        internal static string NoNotificationsYet {
            get {
                return ResourceManager.GetString("NoNotificationsYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No scenario actions yet.
        /// </summary>
        internal static string NoScenarioActionsYet {
            get {
                return ResourceManager.GetString("NoScenarioActionsYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No scenarios yet.
        /// </summary>
        internal static string NoScenariosYet {
            get {
                return ResourceManager.GetString("NoScenariosYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Active.
        /// </summary>
        internal static string NotActive {
            get {
                return ResourceManager.GetString("NotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to now.
        /// </summary>
        internal static string Now {
            get {
                return ResourceManager.GetString("Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        internal static string Paused {
            get {
                return ResourceManager.GetString("Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing.
        /// </summary>
        internal static string Playing {
            get {
                return ResourceManager.GetString("Playing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, check your internet connection and try again.
        /// </summary>
        internal static string PleaseCheckInternet {
            get {
                return ResourceManager.GetString("PleaseCheckInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, select your Smart Home provider.
        /// </summary>
        internal static string PleaseSelectYourSmartHomeProvider {
            get {
                return ResourceManager.GetString("PleaseSelectYourSmartHomeProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, wait.
        /// </summary>
        internal static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, wait a few seconds.
        /// </summary>
        internal static string PleaseWaitFewSeconds {
            get {
                return ResourceManager.GetString("PleaseWaitFewSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Providers.
        /// </summary>
        internal static string Providers {
            get {
                return ResourceManager.GetString("Providers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive Notifications.
        /// </summary>
        internal static string ReceiveNotifications {
            get {
                return ResourceManager.GetString("ReceiveNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rooms.
        /// </summary>
        internal static string Rooms {
            get {
                return ResourceManager.GetString("Rooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario actions.
        /// </summary>
        internal static string ScenarioActions {
            get {
                return ResourceManager.GetString("ScenarioActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenarios.
        /// </summary>
        internal static string Scenarios {
            get {
                return ResourceManager.GetString("Scenarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set temperature.
        /// </summary>
        internal static string SetTemperature {
            get {
                return ResourceManager.GetString("SetTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shades.
        /// </summary>
        internal static string Shades {
            get {
                return ResourceManager.GetString("Shades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in Scenarios.
        /// </summary>
        internal static string ShowInScenarios {
            get {
                return ResourceManager.GetString("ShowInScenarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong.
        /// </summary>
        internal static string SomethingWentWrong {
            get {
                return ResourceManager.GetString("SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, stay in the same Wi-Fi network with your smartphone and mirror to finish synchronozation.
        /// </summary>
        internal static string StayInSameWiFi {
            get {
                return ResourceManager.GetString("StayInSameWiFi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization.
        /// </summary>
        internal static string Synchronization {
            get {
                return ResourceManager.GetString("Synchronization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try Again.
        /// </summary>
        internal static string TryAgain {
            get {
                return ResourceManager.GetString("TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn Off.
        /// </summary>
        internal static string TurnOff {
            get {
                return ResourceManager.GetString("TurnOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn On.
        /// </summary>
        internal static string TurnOn {
            get {
                return ResourceManager.GetString("TurnOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlocked.
        /// </summary>
        internal static string Unlocked {
            get {
                return ResourceManager.GetString("Unlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upstairs Hallway Movement.
        /// </summary>
        internal static string UpstairsHallwayMovement {
            get {
                return ResourceManager.GetString("UpstairsHallwayMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome!.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the Mirror Home app!.
        /// </summary>
        internal static string WelcomeMirrorHome {
            get {
                return ResourceManager.GetString("WelcomeMirrorHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday.
        /// </summary>
        internal static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
    }
}
